### PR TITLE
5909 report bug ux tested

### LINKED ISSUE #5909: Bug-reporting UX
It would be nice if 
a) the `Submit Bug To GitHub` button were to **copy the reported error to the clipboard** and
b) **open this URL**: https://github.com/DynamoDS/Dynamo/issues/new
capture
(I know I can manually copy the error msg but I keep forgetting and hitting that button before doing so...)
Dynamo 0.9 stable

### PR DESCRIPTION
**Pull request by radumg**
### Purpose
NOTE : replaces PR #9150 which was based on wrong branch and adds unit tests.

Fixes #5909 by pre-filling the new Github issue page with 
- an appropriate title that includes Dynamo version number : `Crash report from Dynamo 2.0.1`
- issue body filled with the crash details text, displayed in the `CrashPrompt` window bottom text box

Currently pressing `Submit to Github` takes you here : 

image

With the new behaviour, pressing `Submit to Github` takes you here :
 
image

In the above image, the `This is the error text` body would be replaced by the actual details of the crash stack trace, as per original screenshot in #5909 . 

I can't seem to be able to make Dynamo crash on purpose right now (funny how that works...), so dunno how to replicate.

#### Other notes
- sends users to `https://github.com/DynamoDS/Dynamo/issues/new` by default when no crash text is supplied (friendlier than sending to the super-busy all issues page)
- as per current implementation, you still need to be logged in to Github to be able to submit the issue

#### Further improvements
We could add the rest of the current `issue template` text to the body and wrap the `crash dump` inside a nice code block, but I'm afraid that'd make the query string way too long. Open to ideas/suggestions ?

### Declarations

Check these if you believe they are true

- [x] The code base is in a better state after this PR
- [x] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [x] The level of testing this PR includes is appropriate
- [x] User facing strings, if any, are extracted into `*.resx` files
- [x] All tests pass using the self-service CI.
- [x] Snapshot of UI changes, if any.
- [x] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions), and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### Reviewers
@alfarok 
@Racel 

### FYIs
@andydandy74 , @johnpierson

### CODE REVIEW

**Comment by radumg** [comment]
Started on the unit tests @alfarok , will finish them later today.

For now, confirmed (in a separate experiment) the methodology works for all major browser (on Windows at least) and correctly catches open tabs with right name on : Edge, Chrome, Firefox & even Internet Explorer.

edge
firefox
iexplore
chrome

**Comment by radumg** [comment]
let me know in the meantime if it makes sense where the unit test is placed.

File: test/DynamoCoreWpfTests/CrashReportingTests.cs [hunk 1]
```diff
@@ -0,0 +1,63 @@
...
+using System.Linq;
+using System.Threading;
+using Dynamo.ViewModels;
+using NUnit.Framework;
+
+namespace Dynamo.Tests
+{
+    public class CrashReportingTests : DynamoViewModelUnitTest
+    {
+        public List<string> TargetWords = new List<string> { "New Issue", "DynamoDS" };
```
Comment (mjkkirschner) [inline test/DynamoCoreWpfTests/CrashReportingTests.cs]: private please if possible. It's low importance because this is a test file, but it's good to start conservatively.

**Comment by mjkkirschner** [comment]
@radumg sorry, I should have been more clear. Please keep the test class and tests public (I think they need to be public to be found by nunit on our runner) - I only meant to make the `TargetWords` list private.

😄

**Comment by radumg** [comment]
@mjkkirschner hah, thought there was something funny there, but looked at other classes and they lacked an access modifier, turns out only the methods need. Didn't have the `NUnit 2` adapter anyway, so couldn't test. 😁 

update : confirm it picks up Dynamo version in issue title
image

**Comment by radumg** [comment]
Ok, should be ready for review now @mjkkirschner @alfarok 

Tests passing
tests passing

Works both logged in and logged out of Github
logged out working
logged in working

Now adds long stack trace & further metadata details (OS, CLR & Dynamo versions) to issue body
issue with stack trace

When submitted, it looks like this 
issue formatting

Let me know what you think & if you have any feedback/ideas, etc 😄

**Comment by radumg** [comment]
FYI, introduced a new `CrashUtilities.cs` in `Wpf.Utilities`, it's set to `internal` to not impact public API, hope that's ok - if not, open to suggestions. Didn't want to polute the `ViewModel` with crash formatting implementation details.

**Comment by alfarok** [comment]
Hey @radumg, thanks for continuing this work!  I'll pull your changes today and review

File: src/DynamoCoreWpf/Properties/Resources.Designer.cs [hunk 2]
```diff
@@ -19,7 +19,7 @@ namespace Dynamo.Wpf.Properties
     // class via a tool like ResGen or Visual Studio.
     // To add or remove a member, edit your .ResX file then rerun ResGen
     // with the /str option, or rebuild your VS project.
-    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
+    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
```
Comment (alfarok) [inline src/DynamoCoreWpf/Properties/Resources.Designer.cs]: This can be omitted

File: src/DynamoCoreWpf/Properties/Resources.Designer.cs [hunk 3]
```diff
@@ -747,6 +747,15 @@ public class Resources {
...
         }
         
+        /// <summary>
+        ///   Looks up a localized string similar to Crash report from Dynamo {0}.
+        /// </summary>
+        public static string CrashPromptGithubNewIssueTitle {
+            get {
+                return ResourceManager.GetString("CrashPromptGithubNewIssueTitle", resourceCulture);
+            }
+        }
```
Comment (alfarok) [inline src/DynamoCoreWpf/Properties/Resources.Designer.cs]: Brackets should follow the [coding standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards#conditional-blocks), such as
```C#
public static string CrashPromptGithubNewIssueTitle 
{
    get 
    {
        return ResourceManager.GetString("CrashPromptGithubNewIssueTitle", resourceCulture);
    }
}
```

I do this all the time accidentally switching between C# and Javascript

File: src/DynamoCoreWpf/Utilities/CrashUtilities.cs [hunk 4]
```diff
@@ -0,0 +1,54 @@
...
+        /// <returns>A formatted but not excaped string to use as issue body.</returns>
+        private static string GithhubCrashReportBody(object details)
+        {
+            var content = details?.ToString() ?? string.Empty;
+
+            // This functionality was not available prior to version 2.2, so it should be the fallback value
+            var dynamoVersion = AssemblyHelper.GetDynamoVersion().ToString() ?? "2.2+";
+
+            return
+                "OS: "      + "`"   + Environment.OSVersion + "`"   + Environment.NewLine +
```
Comment (alfarok) [inline src/DynamoCoreWpf/Utilities/CrashUtilities.cs]: Could we add one more line at the top asking for details to reproduce...
```
Description: Please outline all steps required to reproduce the crash including all files and packages
```

I am sure some users will neglect to update the text but if they do it will cut out some additional messaging or we will only address issues that have been filled out completely :grin:

File: src/DynamoCoreWpf/Utilities/CrashUtilities.cs [hunk 5]
```diff
@@ -0,0 +1,54 @@
...
+
+            // this will properly format the string for use as a uri
+            return baseUri.ToString();
+        }
+
+        /// <summary>
+        /// Formats crash details & adds metadata for use in Github issue body
+        /// </summary>
+        /// <param name="details">Crash details, such as a stack trace.</param>
+        /// <returns>A formatted but not excaped string to use as issue body.</returns>
```
Comment (alfarok) [inline src/DynamoCoreWpf/Utilities/CrashUtilities.cs]: *escaped

File: src/DynamoCoreWpf/Utilities/CrashUtilities.cs [hunk 6]
```diff
@@ -0,0 +1,54 @@
...
+            var title = "title=" + Uri.EscapeDataString(string.Format(issueTitle, dynamoVersion));
+            var body = "body=" + Uri.EscapeDataString(content);
+            baseUri.Query = title + "&" + body;
+
+            // this will properly format the string for use as a uri
+            return baseUri.ToString();
+        }
+
+        /// <summary>
+        /// Formats crash details & adds metadata for use in Github issue body
```
Comment (alfarok) [inline src/DynamoCoreWpf/Utilities/CrashUtilities.cs]: I believe `&` is an illegal character in the XML, it can be escaped using `&amp;` or in this case just `and`

**Comment by alfarok** [comment]
@radumg Looks good, just some minor formatting comments.  I am running your branch on the self-serve CI against all the unit tests.  Everything appears to work as expected locally 

image

File: src/DynamoCoreWpf/Utilities/CrashUtilities.cs (hunk 4 above)
Comment (alfarok) [reply src/DynamoCoreWpf/Utilities/CrashUtilities.cs]: This should also help @johnpierson a lot

File: src/DynamoCoreWpf/Properties/Resources.Designer.cs (hunk 3 above)
Comment (radumg) [reply src/DynamoCoreWpf/Properties/Resources.Designer.cs]: that's auto-generated code from Visual Studio (to handle `Resources`) and will be overwritten if I modify anyway - unless i'm missing something ?

**Comment by radumg** [comment]
thanks for the 🚀 review @alfarok !
made all the requested changes (minus the auto-generated code, feel free to do it if low on time).

cleaned up the formatting too, see screenshot below or [sample issue here](https://github.com/DynamoDS/Dynamo/issues/9405)

image

File: src/DynamoCoreWpf/Properties/Resources.Designer.cs (hunk 3 above)
Comment (ColinDayOrg) [reply src/DynamoCoreWpf/Properties/Resources.Designer.cs]: From the comments at the top of the file I believe that this is correct, but if it is auto-generated then it should not be a part of the PR.

Comment (radumg) [reply src/DynamoCoreWpf/Properties/Resources.Designer.cs]: It’s in repo already https://github.com/DynamoDS/Dynamo/blob/master/src/DynamoCoreWpf/Properties/Resources.Designer.cs

File is part of how VisualStudio stores string resources, not something I added

Comment (ColinDayOrg) [reply src/DynamoCoreWpf/Properties/Resources.Designer.cs]: I'm not sure if it matters if it is in the repo or not, just that it will be recreated when the build is run so it is probably not necessary.

Comment (QilongTang) [reply src/DynamoCoreWpf/Properties/Resources.Designer.cs]: Yeah, this is going to be regenerated all the time. The format in `Resources.Designer.cs` should be fine as long as it follows the other resource strings.

**Comment by alfarok** [comment]
Thanks @radumg, LGTM.  I tweaked the template one last time to include some old info we had in there that has been very useful for QA.

image

I ran this branch on the self-serve and it didn't cause any regressions, however the 3 tests you added are failing.  I think it probably has to do either with the test machine not having a working browser or it's slow and exceeding the `Thread.Sleep(4000)` timeout.  I have to get onto the machine to see what's going on because they pass locally.  Will keep you posted!

**Comment by alfarok** [comment]
@radumg quick update, the tests are failing on the test machine because no user is logged in so it brings you to the login page as you outlined.  We can probably just test the body of the request instead and not open the browser at all.  I am looking into a solution now

**Comment by radumg** [comment]
hm, interesting @alfarok ! There's a fallback so the unit test should detect it's on the sign-in page and pass.

In `CrashReportingTests.cs` : 

```cs
private bool ContainsAllTargetWords(string source)
        {
            return TargetWords.TrueForAll(x => source.ToUpper().Contains(x)) ||
                   TargetWordsLoggedOutFallback.TrueForAll(x => source.ToUpper().Contains(x));
        }
```
where the words are : 
```cs
List<string> TargetWordsLoggedOutFallback = new List<string> { "SIGN IN", "GITHUB" };
```

Running it here works logged out too.

**Comment by radumg** [comment]
> @radumg quick update, the tests are failing on the test machine 
What OS is the test machine ? Linux or Windows ? I'm wondering if grabbing the `Process.MainWindowTitle` is inconsistent between them

**Comment by alfarok** [comment]
@radumg I think it is because the test machine opens an additional window about setting a default browser (or something similar) before continuing.  Unfortunately I don't think our testing machines will be super reliable with browser interactions, sorry for any additional work.  I am making a PR to your branch now that simplifies the tests a bit but covers similar functionality.  If we get everything resolved by today we should be able to get this into 2.1

**Comment by alfarok** [comment]
https://github.com/radumg/Dynamo/pull/7

**Comment by radumg** [comment]
All merged in 👍

**Comment by radumg** [comment]
Not sure what’s going with Github, my comments keep disappearing, so just in case :  @alfarok your PR should be merged now, if not please feel free to proceed with it, all looks 👏

**Comment by alfarok** [comment]
@radumg once the self-serve completes I think this is ready to merge if there are no objections from @mjkkirschner.  Thanks for the quick updates the last couple of days, this will be really nice to have in 2.1 :+1:

File: src/DynamoCoreWpf/Utilities/CrashUtilities.cs [hunk 7]
```diff
@@ -0,0 +1,70 @@
...
+    static class CrashUtilities
+    {
+        internal static string GithubNewIssueUrlFromCrashContent(object crashContent)
+        {
+            var baseUri = new UriBuilder(Configurations.GitHubBugReportingLink);
+
+            // provide fallback values for text content in case Resources or Assembly calls fail
+            var issueTitle = Properties.Resources.CrashPromptGithubNewIssueTitle ?? "Crash report from Dynamo {0}";
+            var dynamoVersion = AssemblyHelper.GetDynamoVersion().ToString() ?? "2.1.0+";
+            var content = GithhubCrashReportBody(crashContent);
```
Comment (mjkkirschner) [inline src/DynamoCoreWpf/Utilities/CrashUtilities.cs]: spelling

**Comment by mjkkirschner** [comment]
this looks good to me.

**Comment by alfarok** [comment]
@radumg all unit tests passing, merged.  @QilongTang can I cherry-pick to 2.1?
