### PR TITLE
Fix crash at disposing c# object

### LINKED ISSUE #4533: Getting this bug on latest daily
It was good that the DirectX error is fixed, and node search seems faster.

The managed object is not valid.

   at Autodesk.Revit.RevitAPIManagedWeakPointer<ADocument>.getValidPtr()
   at Autodesk.Revit.DB.Document.GetHashCode()
   at System.Collections.Generic.Dictionary`2.Remove(TKey key)
   at ProtoFFI.CLRObjectMarshler.OnDispose(StackValue dsObject, Context context, Interpreter dsi)
   at ProtoFFI.DisposeFunctionPointer.Execute(Context c, Interpreter dsi)
   at ProtoCore.Lang.FFIFunctionEndPoint.Execute(Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.CallSite.ExecWithZeroRI(List`1 functionEndPoint, Context c, List`1 formalParameters, StackFrame stackFrame, RuntimeCore runtimeCore, FunctionGroup funcGroup, SingleRunTraceData previousTraceData, SingleRunTraceData newTraceData)
   at ProtoCore.CallSite.Execute(List`1 functionEndPoint, Context c, List`1 formalParameters, List`1 replicationInstructions, StackFrame stackFrame, RuntimeCore runtimeCore, FunctionGroup funcGroup)
   at ProtoCore.CallSite.DispatchNew(Context context, List`1 arguments, List`1 partialReplicationGuides, StackFrame stackFrame, RuntimeCore runtimeCore)
   at ProtoCore.DSASM.Executive.Callr(Int32 blockDeclId, Int32 functionIndex, Int32 classIndex, Boolean& explicitCall, Boolean isDynamicCall, Boolean hasDebugInfo)
   at ProtoCore.DSASM.Heap.GCDisposeObject(StackValue svPtr, Executive exe)
   at ProtoCore.DSASM.Heap.GCMarkAndSweep(List`1 rootPointers, Executive exe)
   at ProtoCore.DSASM.Executive.GC()
   at ProtoCore.DSASM.Executive.DEP_Handler(Instruction instruction)
   at ProtoCore.DSASM.Executive.Execute(Int32 exeblock, Int32 entry, Language language)
   at ProtoCore.DSASM.Executive.BounceUsingExecutive(Executive executive, Int32 exeblock, Int32 entry, StackFrame stackFrame, Int32 locals, Boolean fepRun, Executive exec, List`1 breakpoints)
   at ProtoScript.Runners.ProtoScriptTestRunner.ExecuteLive(Core core, RuntimeCore runtimeCore)
   at ProtoScript.Runners.LiveRunner.Execute(Boolean isCodeCompiled)
   at ProtoScript.Runners.LiveRunner.CompileAndExecute(List`1 astList)
   at ProtoScript.Runners.LiveRunner.CompileAndExecuteForDeltaExecution(List`1 astList)
   at ProtoScript.Runners.LiveRunner.UpdateGraph(GraphSyncData syncData)
   at Dynamo.Core.Threading.AsyncTask.Execute()

### PR DESCRIPTION
**Pull request by ke-yu**
### Purpose

This PR is to fix #4533 that Dynamo crashes when disposing some disposable objects. 

When Dynamo imports zero touch libraries, it won't create the corresponding DS classes for all imported C# classes. Instead, it may creates a dummy DS class which contains a dummy `Dispose()` method. PR #4436 is to fix memory leak issue by calling `Dispose()` on this kind of objects, but it causes the crash when `CLRObjectMarshaler` tries to remove DS and C# object from its internal map in the following operation. 

So the fix is to make `CLRObjectMarshaler` cleans up its map before calling `Dispose()` on object. 

### Reviewers

- [x] @sharadkjaiswal

### CODE REVIEW

File: src/Engine/ProtoCore/FFI/CLRFFIFunctionPointer.cs [hunk 1]
```diff
@@ -452,8 +457,8 @@ public override object Execute(ProtoCore.Runtime.Context c, Interpreter dsi)
             else
             {
                 retVal = base.Execute(c, dsi);
+                marshaller.OnDispose(s.Last(), c, dsi); //Notify marshler for dispose.
```
Comment (sharadkjaiswal) [inline src/Engine/ProtoCore/FFI/CLRFFIFunctionPointer.cs]: Can we do something to ensure "marshaller.OnDispose()" is called before the actual dispose of thisObject, otherwise in another scenario this issue will remain unresolved.
